spring.application.name=ConsorCheck

#configuracao da conexao mysql
spring.datasource.url=jdbc:mysql://localhost:3306/db_consorcio?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuracao do JPA /Hibernate
# "validate" garante que o Hibernate apenas valide se o banco bate com as entidades do java, sem tentar criar tabelas sozinho.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do MySQL 8+
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Configuracao do Flyway (migration)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Adicionar threads virtual (acelera processamento de dados sem precisar esperar algo terminar)
#spring.threads.virtual.enabled=true

#Seguranca de tokens jwt
jwt.secret=sM2CBnZg1RXSkJLe3shiAhzpw0yueaaM299/aRMKfI4=
jwt.expiration=86400000
jwt.refresh-expiration=604800000